name: "Build and Publish Docker image"

on:
  workflow_call:
    inputs:
      client:
        description: 'Client name'
        required: true
        type: string
      image_tag:
        description: 'Image tag'
        required: true
        type: string
      image_name:
        description: 'Image registry and name'
        required: true
        type: string
      cosign:
        required: false
        default: false
        type: boolean
        description: 'Run cosign on released image'
      support_platforms:
        required: false
        default: true
        type: boolean
        description: 'Support amd64/arm64'

    secrets:
      quayio-username:
        required: true
      quayio-password:
        required: true

jobs:
  build-image:
    name: Build image and upload to registry
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay.io
        env:
          QUAYIO_USERNAME: ${{ secrets.quayio-username }}
          QUAYIO_PASSWORD: ${{ secrets.quayio-password }}
        run: docker login -u="${QUAYIO_USERNAME}" -p="${QUAYIO_PASSWORD}" quay.io
