name: "Create a Github release"

on:
  workflow_call:
    inputs:
      release_name:
        description: "Name of the release"
        required: true
        type: string
      tag_name:
        description: "Tag used to tag the created release"
        required: true
        type: string
      draft:
        description: "Whether the release is a draft"
        required: false
        type: boolean
        default: false
    outputs:
      upload_url:
        description: "URL where to upload release artifacts"
        value: ${{ jobs.release.outputs.upload_url }}

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ inputs.tag_name }}
          release_name: ${{ inputs.release_name }}
          draft: ${{ inputs.draft }}
          prerelease: false
   
