name: "Release a new version from the main branch"

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      # Do not run the pipeline if only Markdown files changed
      - "**.md"

jobs:
  run_tests:
    uses: ./.github/workflows/test.yaml
    with:
      release: "v1.0.${{ github.run_number }}"
      client: "test"

  create_release:
    uses: ./.github/workflows/create_release.yaml
    needs: "run_tests"
    with:
      release_name: "Release v1.0.${{ github.run_number }}"
      tag_name: "v1.0.${{ github.run_number }}"

  publish_image:
    uses: ./.github/workflows/build_publish_image.yaml
    needs: run_tests
    with:
      client: "image"
      image_name: "quay.io/armo_vladk/kubescape-http"
      image_tag: "test-v1.0.${{ github.run_number }}"
      support_platforms: false
      cosign: true
    secrets:
      quayio-username: ${{ secrets.QUAYIO_ROBOT_USERNAME }}
      quayio-password: ${{ secrets.QUAYIO_ROBOT_PASSWORD }}
